---
title: "Data Import"
author: "Kristi Chau"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

## Load in Dataset

```{r}
## reads in a dataset (absolute (NO) vs relative (YES) paths)
## read_csv brings dataset into a tibble, read.csv is more lax

litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data) ## rewriting dataset

pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
## pups_data_abs = read_csv(file = "C:/Users/kchau/Documents/Columbia Mailman/Columbia Mailman - Fall 2019/Data Science/Class Examples/data_import/data/FAS_pups.csv")

## litters_data = read_csv(file = "./data/FAS_litters.csv",
##   skip = 10, col_names = FALSE)
```

## Play with column parsing (how variables are read in)

```{r}
litters_data = read_csv(
  file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(), ## in back ticks, bc varname includes a space,   needs to be recognized as variable
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```

## Read in an excel file

```{r}
mlb11_data = read_excel(path = "./data/mlb11.xlsx")

```

## Read in SAS

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```

## Selecting!

```{r}
select(litters_data, group, litter_number) ## (dataframe, col1, col2, etc.)

select(litters_data, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight) ## listed order matters

select(litters_data, litter_number, group, everything())

select(litters_data, -group) ## "-" remove a column

select(litters_data, litter_number, gd0_weight:pups_born_alive) ## ":" keep everything bw these two variables

select(litters_data, GROUP = group, litter_number) ## renamed "group"

rename(litters_data, GROUP = group) ## just a rename function
```

## Filtering!

```{r}
filter(litters_data, group == "Con7") ## "==" differs between an assignment and a logical question, keep group when equal to Con7

filter(litters_data, gd_of_birth == 20) ## numeric variables

filter(litters_data, pups_born_alive < 6, group == "Con7")

filter(litters_data, group == "Con7" | group == "Mod8") ## "or" logical
filter(litters_data, group %in% c("Con7", "Mod8"))

filter(litters_data, pups_born_alive >= 4 , pups_born_alive <= 6) ## a range

filter(litters_data, gd0_weight + gd18_weight < 70)

# don't do this: filter(litters_data, !is.na(gd0_weight))
drop_na(litters_data, gd0_weight)
```

## Mutate

```{r}
mutate(
  litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)) ## what is the difference with tolower function
```


## Arrange (ORDERING THINGS!)

```{r}
arrange(litters_data, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))

arrange(litters_data, pups_born_alive, gd0_weight) ## first sort by pups_born_alive, then within that, order by gd0_weight
```


